import { Injectable } from '@angular/core';

@Injectable()
export class SheardService {

  constructor() { }
  visibleImages=[];

  getImages(){
    return this.visibleImages= IMAGES.slice(0);
  }

}

const IMAGES = [
  {"id": 1, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/2.jpg"},
  {"id": 2, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/3.jpg"},
  {"id": 3, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/4.jpg"},
  {"id": 4, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/5.jpg"},
  {"id": 5, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/6.jpg"},
  {"id": 6, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/7.jpg"},
  {"id": 7, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/8.jpg"},
  {"id": 8, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/9.jpg"},
  {"id": 9, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/10.jpg"},
  {"id": 10, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/12.jpg"},
  {"id": 11, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/11.jpg"},
  {"id": 12, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img2.jpg"},
  {"id": 13, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img3.jpg"},
  {"id": 14, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img4.jpg"},
  {"id": 15, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img12.jpg"},
  {"id": 16, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img5.jpg"},
  {"id": 17, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img6.jpg"},
  {"id": 18, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img7.jpg"},
  {"id": 19, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img9.jpg"},
  {"id": 20, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img10.jpg"},
  {"id": 21, "category": "lehenga", "caption":"view From a lehenga", "url":"assets/images/portfolioes/lehenga/2.jpg"},
  {"id": 22, "category": "lehenga", "caption":"view From a lehenga", "url":"assets/images/portfolioes/lehenga/6.jpg"},
  {"id": 23, "category": "lehenga", "caption":"view From a lehenga", "url":"assets/images/portfolioes/lehenga/3.jpg"},
  {"id": 24, "category": "lehenga", "caption":"view From a lehenga", "url":"assets/images/portfolioes/lehenga/4.jpg"},
  {"id": 25, "category": "lehenga", "caption":"view From a lehenga", "url":"assets/images/portfolioes/lehenga/5.jpg"},
  {"id": 26, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/1.jpg"},
  {"id": 27, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/2.jpg"},
  {"id": 28, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/3.jpg"},
  {"id": 29, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/4.jpg"},
  {"id": 30, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/5.jpg"},
  {"id": 31, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/6.jpg"},
  {"id": 32, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/7.jpg"},
  {"id": 33, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/8.jpg"},
  {"id": 34, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/12.jpg"},
  {"id": 35, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/13.jpg"},
  {"id": 36, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/14.jpg"},
  {"id": 37, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/15.jpg"},
  {"id": 38, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/16.jpg"},
  {"id": 39, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/17.jpg"},
  {"id": 40, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/18.jpg"},
  {"id": 41, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/19.jpg"},
  {"id": 42, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/20.jpg"},
  {"id": 43, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/21.jpg"},
  {"id": 44, "category": "bracelates", "caption":"view From a bracelates", "url":"assets/images/portfolioes/bracelates/22.jpg"},
  {"id": 45, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img11.jpg"},
  {"id": 46, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img12.jpg"},
  {"id": 47, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img13.jpg"},
  {"id": 48, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img14.jpg"},
  {"id": 49, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img15.jpg"},
  {"id": 50, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img16.jpg"},
  {"id": 51, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img17.jpg"},
  {"id": 52, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img18.jpg"},
  {"id": 53, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img19.jpg"},
  {"id": 54, "category": "frocks", "caption":"view From a frocks", "url":"assets/images/portfolioes/frocks/img21.jpg"},
  {"id": 55, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/36.jpg"},
  {"id": 56, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/2.jpg"},
  {"id": 57, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/3.jpg"},
  {"id": 58, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/4.jpg"},
  {"id": 59, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/5.jpg"},
  {"id": 60, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/6.jpg"},
  {"id": 61, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/7.jpg"},
  {"id": 62, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/35.jpg"},
  {"id": 63, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/31.jpg"},
  {"id": 64, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/32.jpg"},
  {"id": 65, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/33.jpg"},
  {"id": 66, "category": "sarees", "caption":"view From a sarees", "url":"assets/images/portfolioes/sarees/34.jpg"},
  {"id": 67, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img1.jpg"},
  {"id": 68, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img2.jpg"},
  {"id": 69, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img3.jpg"},
  {"id": 70, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img4.jpg"},
  {"id": 71, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img5.jpg"},
  {"id": 72, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img6.jpg"},
  {"id": 73, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img7.jpg"},
  {"id": 74, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img8.jpg"},
  {"id": 75, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img9.jpg"},
  {"id": 76, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img10.jpg"},
  {"id": 77, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img11.jpg"},
  {"id": 78, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img12.jpg"},
  {"id": 79, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img13.jpg"},
  {"id": 80, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img14.jpg"},
  {"id": 81, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img15.jpg"},
  {"id": 82, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img16.jpg"},
  {"id": 83, "category": "watches", "caption":"view From a watches", "url":"assets/images/portfolioes/watches/img17.jpg"},


]
